Description: >
  Udagram
Parameters:
  EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
Resources:
  IAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
  ProfileWithRolesForOurApp:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: /
      Roles:
        -  Ref: "IAMRole"
Outputs: 
  IAMRole:
    Description: "Allows EC2 instances to manage Web App S3"
    Value: !Ref ProfileWithRolesForOurApp
    Export:
      Name: !Sub ${EnvironmentName}-IAM-NAME
  IAMRoleArn:
    Description: Iam Instance Profile Arn
    Value: !GetAtt IAMRole.Arn
    Export:
      Name: !Sub ${EnvironmentName}-IAM-ARN